//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMSBackUpCenterService.Forms.HashServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HashService.HashingTypes", Namespace="http://schemas.datacontract.org/2004/07/KMSBackUpCenterService")]
    public enum HashServiceHashingTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MD5 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SHA1 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SHA256 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SHA384 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SHA512 = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HashServiceReference.IHashService")]
    public interface IHashService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHashService/GetChecksum", ReplyAction="http://tempuri.org/IHashService/GetChecksumResponse")]
        string GetChecksum(KMSBackUpCenterService.Forms.HashServiceReference.HashServiceHashingTypes hashingType, string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHashService/GetChecksum", ReplyAction="http://tempuri.org/IHashService/GetChecksumResponse")]
        System.Threading.Tasks.Task<string> GetChecksumAsync(KMSBackUpCenterService.Forms.HashServiceReference.HashServiceHashingTypes hashingType, string filename);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHashServiceChannel : KMSBackUpCenterService.Forms.HashServiceReference.IHashService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HashServiceClient : System.ServiceModel.ClientBase<KMSBackUpCenterService.Forms.HashServiceReference.IHashService>, KMSBackUpCenterService.Forms.HashServiceReference.IHashService {
        
        public HashServiceClient() {
        }
        
        public HashServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HashServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HashServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HashServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetChecksum(KMSBackUpCenterService.Forms.HashServiceReference.HashServiceHashingTypes hashingType, string filename) {
            return base.Channel.GetChecksum(hashingType, filename);
        }
        
        public System.Threading.Tasks.Task<string> GetChecksumAsync(KMSBackUpCenterService.Forms.HashServiceReference.HashServiceHashingTypes hashingType, string filename) {
            return base.Channel.GetChecksumAsync(hashingType, filename);
        }
    }
}
